{"amnt": "1", "subtitle": "Ambassador of Fear", "name": "Doc Scarecrow", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/c/cb/Boss_Monster_Clerics.PNG/revision/latest/scale-to-width-down/227?cb=20150505222408", "treasure": "Cleric", "link": "/wiki/Doc_Scarecrow", "stats": "375", "type": "Boss", "id": "TNL001", "desc": "Level Up:\n For the rest of the game, during the Build phase you may discard one card to choose one Hero in town. That Hero cannot be lured this turn."}
{"amnt": "1", "subtitle": "The Beckoner", "name": "Torix Uz'Kali", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/3/36/White_dragon.JPG/revision/latest?cb=20150309175952", "treasure": "Cleric", "link": "/wiki/Torix_Uz%27Kali", "stats": "725", "type": "Boss", "id": "TNL003", "desc": "Level Up:\n For the rest of the game, whenever any Monster Room is discarded or destroyed, you may put it into your hand."}
{"amnt": "1", "subtitle": "Mad Alchemist", "name": "Dr. Timebender", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/a/a5/Boss_Monster_Mages.PNG/revision/latest/scale-to-width-down/220?cb=20150506021525", "treasure": "Mage", "link": "/wiki/Dr._Timebender", "stats": "925", "type": "Boss", "id": "TNL008", "desc": "Level Up:\n For the rest of the game, once per turn you may discard a Spell card to cancel an opponent's Spell."}
{"amnt": "1", "subtitle": "The Dwarfbane", "name": "Smoake", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/3/30/Red_dragon.JPG/revision/latest/scale-to-width-down/412?cb=20150309175425", "treasure": "Fighter", "link": "/wiki/Smoake", "stats": "625", "type": "Boss", "id": "TNL006", "desc": "Level Up:\n For the rest of the game, whenever you build a Monster Room, you may Draw a Room card."}
{"amnt": "1", "subtitle": "Man-Eating Ape", "name": "Killa", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/a/a3/BM2_Killa.jpg/revision/latest/scale-to-width-down/300?cb=20150309172537", "treasure": "Fighter", "link": "/wiki/Killa", "stats": "825", "type": "Boss", "id": "TNL004", "desc": "Level Up:\n For the rest of the game, if you have 3 Wounds or more, give the last Room of your dungeon +3"}
{"amnt": "1", "subtitle": "Vampire Baroness", "name": "Belladonna", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/9/98/BM2_Belladonna_fixed.png/revision/latest/scale-to-width-down/346?cb=20150327102020", "treasure": "Cleric", "link": "/wiki/Belladonna", "stats": "350", "type": "Boss", "id": "TNL002", "desc": "Level Up:\n Heal a Wound. (Turn one face-down Hero face-up.)"}
{"amnt": "1", "subtitle": "The Arcane Dragon", "name": "Nicolius", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/a/ac/Blue_dragon.JPG/revision/latest/scale-to-width-down/412?cb=20150309175632", "treasure": "Mage", "link": "/wiki/Nicolius", "stats": "975", "type": "Boss", "id": "TNL009", "desc": "Level Up:\n For the rest of the game, you may draw a Spell card at the end of turn if any player has gained two more souls than you that turn."}
{"amnt": "1", "subtitle": "King of Thieves", "name": "Porkus", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/0/0f/Boss_Monster_Thief.PNG/revision/latest/scale-to-width-down/220?cb=20150506021948", "treasure": "Thief", "link": "/wiki/Porkus", "stats": "450", "type": "Boss", "id": "TNL010", "desc": "Level Up:\n Choose one face-down Hero from your scorekeeping area and remove it from the game. Search the Hero decks, choose one Hero, and place it face-down in your scorekeeping area."}
{"amnt": "1", "subtitle": "Genie of Games", "name": "Kazanna", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/a/a5/Boss_Monster_Mages.PNG/revision/latest/scale-to-width-down/220?cb=20150506021525", "treasure": "Mage", "link": "/wiki/Kazanna", "stats": "550", "type": "Boss", "id": "TNL007", "desc": "Level Up:\n Discard your hand, then draw 3 Spell cards."}
{"amnt": "1", "subtitle": "Kappa Princess", "name": "Shellda", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/e/ec/BM2_Shellda.jpg/revision/latest/scale-to-width-down/220?cb=20150309172112", "treasure": "Fighter", "link": "/wiki/Shellda", "stats": "425", "type": "Boss", "id": "TNL005", "desc": "Level Up:\n For the rest of the game, at end of turn you may swap the placement of two Rooms in one dungeon."}
{"amnt": "1", "subtitle": "Advanced Monster Room", "name": "Incubus Gym", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/0/07/Incubus_gym.png/revision/latest/scale-to-width-down/300?cb=20150327002448", "treasure": "Cleric", "link": "/wiki/Incubus_Gym", "stats": "4", "type": "Room", "id": "TNL019", "desc": "When you build this Room, each opponent must discard a Room card."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Madman's Manor", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/6/6b/Madman%27s_manor.jpg/revision/latest/scale-to-width-down/300?cb=20150415165458", "treasure": "Cleric", "link": "/wiki/Madman%27s_Manor", "stats": "2", "type": "Room", "id": "TNL015", "desc": "Once per turn, if a Hero dies in this Room, choose one Spell card from the discard pile and put it into your hand."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Haunted Hall", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/1/11/Haunted_hall.jpg/revision/latest/scale-to-width-down/300?cb=20150415164407", "treasure": "Cleric", "link": "/wiki/Haunted_Hall", "stats": "2", "type": "Room", "id": "TNL017", "desc": "You may destroy this Room to send a Hero in this Room back to town."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Arcane Crypt", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/0/05/Arcane_crypt.jpg/revision/latest/scale-to-width-down/300?cb=20150415163412", "treasure": "Cleric", "link": "/wiki/Arcane_Crypt", "stats": "1", "type": "Room", "id": "TNL016", "desc": "When you build or uncover this Room, you may choose one Spell card from the discard pile and put it into your hand."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Thief", "min": "6", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/0/04/BMA078_Francisco_the_Endbringer.jpg/revision/latest/scale-to-width-down/300?cb=20121219062415", "treasure": "Thief", "link": "/wiki/Francisco_the_Endbringer", "stats": "6", "type": "Hero", "id": "TNL094", "desc": "Francisco the Endbringer\n\n\nThis highly trained assassin from the southern Silver Kingdom is known as the \"painter or blood.\""}
{"amnt": "1", "subtitle": "Epic Hero", "name": "The Brothers", "min": "\u2605", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/a/a4/The_brothers-0.jpg/revision/latest/scale-to-width-down/300?cb=20150415165310", "treasure": "?", "link": "/wiki/The_Brothers", "stats": "20", "type": "Hero", "id": "TNL114", "desc": "This Hero is lured to the dungeon of the player with the highest total Souls minus Wounds."}
{"amnt": "1", "subtitle": "Epic Hybrid Hero", "name": "Archer", "min": "\u2605", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/d/de/Archer.PNG/revision/latest/scale-to-width-down/220?cb=20150506025822", "treasure": "Fighter / Thief", "link": "/wiki/Archer", "stats": "12", "type": "Hero", "id": "TNL112", "desc": "This Hero is lured to the dungeon with the highest combined Fighter and Thief treasure. This Hero ignores the last Room of your dungeon.\n\nRevised: \nThis Hero is lured to the dungeon with the highest combined Fighter and Thief treasure. This Hero skips the last Room of your dungeon."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Imp Temple", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/4/4c/Imp_Temple.PNG/revision/latest/scale-to-width-down/220?cb=20150506222310", "treasure": "Cleric*2", "link": "/wiki/Imp_Temple", "stats": "1", "type": "Room", "id": "TNL014", "desc": "Once per turn, when you force an opponent to discard a card, put that card into your hand instead."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Mage", "min": "4", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/8/88/Markus.jpg/revision/latest/scale-to-width-down/180?cb=20160505215606", "treasure": "Mage", "link": "/wiki/Markus,_Geomancer_Supreme", "stats": "13", "type": "Hero", "id": "TNL109", "desc": "Markus, Geomancer Supreme\n\n\nOnce, he lived alone in a flat, infinite world. Alone, he braved its depths and dangers to mine its riches. Then this unaccompanied miner had a dream. He dreamed he could create anything, even entire worlds, and each world he created held a dreamer of its own."}
{"amnt": "1", "subtitle": "Epic Hybrid Hero", "name": "Druid", "min": "\u2605", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/c/ca/Druid.PNG/revision/latest/scale-to-width-down/220?cb=20150506031807", "treasure": "Cleric / Mage", "link": "/wiki/Druid", "stats": "12", "type": "Hero", "id": "TNL108", "desc": "This Hero is lured to the dungeon with the highest combined Cleric and Mage treasure. Give this Hero +X, where X equals the number of Spell cards in your hand."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Inner Sanctum", "min": "-", "img_url": "", "treasure": "Cleric", "link": "/wiki/Inner_Sanctum?action=edit&redlink=1", "stats": "2", "type": "Room", "id": "TNL018", "desc": "At the end of each turn, if no Heroes entered this Room, you may draw a Room card."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Thief", "min": "2", "img_url": "", "treasure": "Thief", "link": "/wiki/Rom_the_Reaver?action=edit&redlink=1", "stats": "11", "type": "Hero", "id": "TNL110", "desc": "Rom the Reaver\n\n\nNo one is faster with a blade, but Rom is a tortured soul. It's as if a monster lurks inside him, and the dungeon is the only safe place to channel his rage."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Thief", "min": "3", "img_url": "", "treasure": "Thief", "link": "/wiki/Gaimina,_Thief_of_Dreams?action=edit&redlink=1", "stats": "11", "type": "Hero", "id": "TNL111", "desc": "Gaimina, Thief of Dreams\n\n\nNo door is closed to her, nor any dreaming mind, and she does not fear death. But Gaimina's light steps cast long shadows, and she must never let them overtake her."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Thief", "min": "4", "img_url": "", "treasure": "Thief", "link": "/wiki/Roberta,_Dreaded_Outlaw?action=edit&redlink=1", "stats": "13", "type": "Hero", "id": "TNL113", "desc": "Roberta, Dreaded Outlaw\n\n\nHer life became a nightmare when she was wedded to an evil prince and her true love was slain by a pirate. Roberta took vengeance on both, and now she does as she wishes."}
{"amnt": "1", "subtitle": "Epic Hybrid Hero", "name": "Swordmage", "min": "\u2605", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/3/36/Swordmage.jpg/revision/latest/scale-to-width-down/300?cb=20150415163820", "treasure": "Mage / Fighter", "link": "/wiki/Swordmage", "stats": "12", "type": "Hero", "id": "TNL104", "desc": "This Hero is lured to the dungeon with the highest combined Mage and Fighter treasure. Each time a player plays a Spell while this Hero is in your dungeon, give this Hero +2"}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Fighter", "min": "3", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/2/22/Ser_Mortin_the_Deadly.jpg/revision/latest/scale-to-width-down/300?cb=20150427234932", "treasure": "Fighter", "link": "/wiki/Ser_Mortin_the_Deadly", "stats": "11", "type": "Hero", "id": "TNL103", "desc": "Ser Mortin the Deadly\n\n\nNo knight is more celebrated, but do not invite Ser Mortin to your wedding feast. Many and more have died to his blade, the noble as well as the wicked..."}
{"amnt": "1", "subtitle": "Advanced Trap Room", "name": "Chump Chomper", "min": "-", "img_url": "", "treasure": "Thief", "link": "/wiki/Chump_Chomper?action=edit&redlink=1", "stats": "2", "type": "Room", "id": "TNL046", "desc": "Once per turn, you may destroy another Room in your dungeon to give this Room +4 until end of turn."}
{"amnt": "1", "subtitle": "Epic Hybrid Hero", "name": "Necromancer", "min": "\u2605", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/9/96/Necromancer.PNG/revision/latest/scale-to-width-down/220?cb=20150506030708", "treasure": "Cleric / Fighter", "link": "/wiki/Necromancer", "stats": "12", "type": "Hero", "id": "TNL100", "desc": "This Hero is lured to the dungeon with the highest combined Mage and Fighter treasure. Each time a player plays a Spell while this Hero is in your dungeon, give this Hero +2."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Mage", "min": "2", "img_url": "", "treasure": "Mage", "link": "/wiki/Dumbledalf_the_Blue?action=edit&redlink=1", "stats": "11", "type": "Hero", "id": "TNL106", "desc": "Dumbledalf the Blue\n\n\nIn a world of punk-rock pyromancers and spiky haired sorcerers, one man believes in keeping things classic. Dumbledalf proves that flowing beards and pointy hats never go out of fashion."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Mage", "min": "3", "img_url": "", "treasure": "Mage", "link": "/wiki/Wrathfuss_the_Namer?action=edit&redlink=1", "stats": "11", "type": "Hero", "id": "TNL107", "desc": "Wrathfuss the Namer\n\n\nWrathfuss knew the names of most things, and so most things were his to command. He said to the wind: \"Break!\" and the wind broke."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Fighter", "min": "4", "img_url": "", "treasure": "Fighter", "link": "/wiki/O%27Brien_the_Destroyer?action=edit&redlink=1", "stats": "13", "type": "Hero", "id": "TNL105", "desc": "O'Brien the Destroyer\n\n\nEvery night, he begins a new quest for glory. This savage redhead has survived the rise and fall of many rivals. He knows what is best in life, and in the end, he will triumph."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "The Fool", "min": "2", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/e/ef/BMA080_The_Fool.jpg/revision/latest/scale-to-width-down/300?cb=20130211193631", "treasure": "?", "link": "/wiki/The_Fool", "stats": "2", "type": "Hero", "id": "TNL097", "desc": "The Fool is lured to the dungeon of the player with the fewest Souls. (In the case of a tie, he waits in town until the tie is broken.)"}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Hitman", "min": "\u2605", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/c/c2/Hitman.PNG/revision/latest/scale-to-width-down/220?cb=20150506213357", "treasure": "Thief", "link": "/wiki/Hitman", "stats": "6", "type": "Hero", "id": "TNL095", "desc": "Once per turn, any opponent may discard a Room with Thief to give this Hero +3 until end of turn."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Fighter", "min": "2", "img_url": "", "treasure": "Fighter", "link": "/wiki/Lone_Fox_and_Kit?action=edit&redlink=1", "stats": "11", "type": "Hero", "id": "TNL102", "desc": "Lone Fox and Kit\n\n\nFew know that this mysterious beauty was once a princess. With her daughter on her back, she uses her skills with the sword to seek victory against those who deposed her."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Cleric", "min": "4", "img_url": "", "treasure": "Cleric", "link": "/wiki/Heavenboy?action=edit&redlink=1", "stats": "13", "type": "Hero", "id": "TNL101", "desc": "Heavenboy\n\n\nThis son of an angel and a mortal woman was born with clipped wings and half a halo. Now he fights evil with a holy blade and a golden gauntlet known as The Right Hand of Boon."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Mage", "min": "4", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/d/df/TNL090_Mage_8_Iskandar.png/revision/latest/scale-to-width-down/294?cb=20150809222120", "treasure": "Mage", "link": "/wiki/Iskandar,_Ice_Mage", "stats": "8", "type": "Hero", "id": "TNL090", "desc": "Iskandar, Ice Mage\n Once a small-town librarian, Iskandar became a hero when he defended his town against a dragon attack. Now he seeks to use his chilling ice magic to bring down the dragons of Arcadia."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Cleric", "min": "3", "img_url": "", "treasure": "Cleric", "link": "/wiki/Branadin_Wordblessed?action=edit&redlink=1", "stats": "11", "type": "Hero", "id": "TNL099", "desc": "Branadin Wordblessed\n This cosmic chronicler travels tirelessly from world to world, inscribing each people's histories and magics on plates of copper. He never stops writing...except to battle the forces of darkness."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Thief", "min": "2", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/a/a9/Black_Leaf.png/revision/latest/scale-to-width-down/412?cb=20150309173440", "treasure": "Thief", "link": "/wiki/Black_Leaf", "stats": "4", "type": "Hero", "id": "TNL091", "desc": "Black Leaf\n Black Leaf is always the first to scout ahead, swing across a chasm, or disable a poins trap. She always says there's no danger she's afraid to face, except a life without adventure."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Witch", "min": "\u2605", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/0/01/Witch.PNG/revision/latest/scale-to-width-down/220?cb=20150506213753", "treasure": "Mage", "link": "/wiki/Witch", "stats": "6", "type": "Hero", "id": "TNL089", "desc": "Once per turn, any opponent may discard a Room with Mage to give this Hero +3 until end of turn."}
{"amnt": "1", "subtitle": "Epic Hero", "name": "Cleric", "min": "2", "img_url": "", "treasure": "Cleric", "link": "/wiki/Tyrone,_Pharaoh_Ascendant?action=edit&redlink=1", "stats": "11", "type": "Hero", "id": "TNL098", "desc": "Tyrone, Pharaoh Ascendant\n When Tyrone was young, the temple elders praised his hieroglyphics. But what began as mere artistry grew into miraculous power. Now his wisdom is revered throughout Arcadia."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Thief", "min": "4", "img_url": "", "treasure": "Thief", "link": "/wiki/Raymond_Two-Chains?action=edit&redlink=1", "stats": "8", "type": "Hero", "id": "TNL096", "desc": "Raymond Two-Chains\n Once he was an outlaw, notorious for wielding his chain-whips with deadly precision. Now he's a man one a mission. He tracks the Croaking King across dimensions, and will stop at nothing to find him."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Thief", "min": "2", "img_url": "", "treasure": "Thief", "link": "/wiki/Colgar,_Fugitive_Prince?action=edit&redlink=1", "stats": "6", "type": "Hero", "id": "TNL093", "desc": "Colgar, Fugitive Prince\n He lost his kingdom to Cerebellus, but he retains his ancestral weapon. Now this royal rogue must use his disk-glaive and his wits to regain his thone...or at least his honor."}
{"amnt": "1", "subtitle": "Ordinary Dark Hero", "name": "Barbarian", "min": "\u2605", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/a/a8/Barbarian.PNG/revision/latest/scale-to-width-down/220?cb=20150506213001", "treasure": "Fighter", "link": "/wiki/Barbarian", "stats": "6", "type": "Hero", "id": "TNL083", "desc": "Once per turn, any opponent may discard a Room with Fighter to give this Hero +3 until end of turn."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Thief", "min": "4", "img_url": "", "treasure": "Thief", "link": "/wiki/Murphy_the_Magnificent?action=edit&redlink=1", "stats": "4", "type": "Hero", "id": "TNL092", "desc": "Murphy the Magnificent\n He was a charlatan, a carnival performer, and a con man ...all before he turned sixteen. When he delved into his first dungeon, he discovered he was something else: a hero."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Mage", "min": "2", "img_url": "", "treasure": "Mage", "link": "/wiki/Megan_the_Missile_Mage?action=edit&redlink=1", "stats": "4", "type": "Hero", "id": "TNL085", "desc": "Megan the Missile Mage\n This intrepid adventuress, also known as \"the Azure Evoker,\" is not your typical wizard. Specializing in magic missiles, she'd rather be battling monsters than studying dusty tomes."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Mage", "min": "3", "img_url": "", "treasure": "Mage", "link": "/wiki/Wink_the_Probably_Magical?action=edit&redlink=1", "stats": "6", "type": "Hero", "id": "TNL088", "desc": "Wink the Probably Magical\n Wink's apparent lack of magical talent has not stopped him from going on adventures, or referring to his pet chameleon as his \"familiar.\" But so far, everything's going well."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Mage", "min": "4", "img_url": "", "treasure": "Mage", "link": "/wiki/Otus_the_Occult?action=edit&redlink=1", "stats": "4", "type": "Hero", "id": "TNL086", "desc": "Otus the Occult\n Otus has seen things that the would drive most mortal men to madness. But he is a man of vision, and a touch of insanity only makes his magic more powerful."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Mage", "min": "2", "img_url": "", "treasure": "Mage", "link": "/wiki/A_Kid_and_His_Spellslime?action=edit&redlink=1", "stats": "6", "type": "Hero", "id": "TNL087", "desc": "A Kid and His Spellslime\n When an ordinary kid discovered a wounded spellslime, he nursed it back to health with candy. The spellslime rewarded his kindness with an adventure to a world of magic."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Fighter", "min": "4", "img_url": "", "treasure": "Fighter", "link": "/wiki/Damok,_Dragon_Hunter?action=edit&redlink=1", "stats": "8", "type": "Hero", "id": "TNL084", "desc": "Damok, Dragon Hunter\n Some regard him as a savage for his primitive weaponry, and his speech consists of cryptic phrases like \"Scythe, his face black, his eyes red.\" But none doubt Damok's skill in battle."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Cleric", "min": "4", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/d/db/TNL078_Cleric_8_Adynn.png/revision/latest/scale-to-width-down/278?cb=20150809221919", "treasure": "Cleric", "link": "/wiki/Adynn,_Cleric_of_Love", "stats": "8", "type": "Hero", "id": "TNL078", "desc": "Adynn, Cleric of Love\n The son of a philandering elf, Adynn inherited his father's charm and beauty. As a missionary Cleric of the Goddess of Love, he is always eager to practice what he preaches."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Fighter", "min": "3", "img_url": "", "treasure": "Fighter", "link": "/wiki/Ampersand_the_Galled?action=edit&redlink=1", "stats": "6", "type": "Hero", "id": "TNL082", "desc": "Ampersand the Galled\n This dwarven warrior is legendary for his prodigious appetite, his puissant skill at arms, and his crazy temper. What he lacks in height he makes up for in rage fueled strength."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Fighter", "min": "2", "img_url": "", "treasure": "Fighter", "link": "/wiki/Lady_Samantha?action=edit&redlink=1", "stats": "6", "type": "Hero", "id": "TNL081", "desc": "Lady Samantha\n Her skills as a weaponsmith made Lady Samantha one of the wealthiest nobles in Arcadia. In search of greater glory, she armed herself to the teeth and set off to hunt for the Brainsucker Queen."}
{"amnt": "1", "subtitle": "Ordinary Dark Hero", "name": "Vampire", "min": "\u2605", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/4/4e/Vampire.png/revision/latest/scale-to-width-down/350?cb=20150311185847", "treasure": "Cleric", "link": "/wiki/Vampire", "stats": "6", "type": "Hero", "id": "TNL077", "desc": "Once per turn, any opponent may discard a Room with Cleric to give this Hero +3 until end of turn."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Cleric", "min": "4", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/e/e4/BMA059_Kyle_the_Incorruptible.jpg/revision/latest/scale-to-width-down/300?cb=20121219055953", "treasure": "Cleric", "link": "/wiki/Kyle_the_Incorruptible", "stats": "4", "type": "Hero", "id": "TNL074", "desc": "Kyle the Incorruptible\n This acolyte of the Order declared himself free from sin and immune to temptation ...an unwavering agent of virtue."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Fighter", "min": "4", "img_url": "", "treasure": "Fighter", "link": "/wiki/Tarka,_Eskimo_Warrior?action=edit&redlink=1", "stats": "4", "type": "Hero", "id": "TNL080", "desc": "Tarka, Eskimo Warrior\n This northern warrior will not rest until he finds his best friend. No dungeon is too deep to delve, no mountain too high to climb. He'll do whatever it takes to bring his buddy home."}
{"amnt": "2", "subtitle": "-", "name": "Wild Monster", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/4/42/Wild_Monster.PNG/revision/latest/scale-to-width-down/220?cb=20150506202107", "treasure": "-", "link": "/wiki/Wild_Monster", "stats": "Adventure", "type": "Spell", "id": "TNL072", "desc": "You may immediately build a Monster Room over an existing Room in your dungeon."}
{"amnt": "2", "subtitle": "-", "name": "Surprise Gift", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/4/46/Surprise_gift-0.jpg/revision/latest/scale-to-width-down/300?cb=20150415165732", "treasure": "-", "link": "/wiki/Surprise_Gift", "stats": "Build", "type": "Spell", "id": "TNL070", "desc": "During the Build phase, you may place a Room in an opponent's dungeon instead of your own. (Place it face-down over a face-up Room. Opponent may still place another Room. Any build effects apply to the opponent.)"}
{"amnt": "2", "subtitle": "-", "name": "Super Effective!", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/7/77/Super_Effective%21_%28goofed_card%29.PNG/revision/latest/scale-to-width-down/220?cb=20150506203031", "treasure": "-", "link": "/wiki/Super_Effective!", "stats": "Adventure", "type": "Spell", "id": "TNL069", "desc": "Choose a Room in your dungeon. It deals +2 until end of turn. OR If only one Hero was lured to your dungeon this turn, that Room does +4 until end of turn."}
{"amnt": "2", "subtitle": "-", "name": "Shortcut!", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/6/63/Shortcut.jpg/revision/latest/scale-to-width-down/300?cb=20150415164904", "treasure": "-", "link": "/wiki/Shortcut!", "stats": "Adventure", "type": "Spell", "id": "TNL068", "desc": "Choose a Hero in any dungeon. It skips the next Room it would enter. OR If that dungeon has five Rooms, the Hero skips the next two Rooms it would enter."}
{"amnt": "2", "subtitle": "-", "name": "Undead Minion", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/c/c1/Undead_minion.jpg/revision/latest/scale-to-width-down/300?cb=20150427235300", "treasure": "-", "link": "/wiki/Undead_Minion", "stats": "Adventure", "type": "Spell", "id": "TNL071", "desc": "Choose one face-down Hero in your scorekeeping area and remove it from the game. Deal damage equal to that Hero's Health to one Hero in your dungeon."}
{"amnt": "2", "subtitle": "-", "name": "Pity", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/3/3d/Pity.PNG/revision/latest/scale-to-width-down/220?cb=20150506201644", "treasure": "-", "link": "/wiki/Pity", "stats": "Adventure", "type": "Spell", "id": "TNL066", "desc": "Choose a Hero in an opponent's dungeon. Remove that Hero from the game."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Fighter", "min": "2", "img_url": "", "treasure": "Fighter", "link": "/wiki/Hookshot_Joe?action=edit&redlink=1", "stats": "4", "type": "Hero", "id": "TNL079", "desc": "Hookshot Joe\n Once the commander of an elite fighting unit, he lost his left hand in battle. Now, with a grappling hook permanently fused to his arm, Hookshot Joe carries on the fight."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Cleric", "min": "3", "img_url": "", "treasure": "Cleric", "link": "/wiki/Solemn_Caine,_Pilgrim_of_Pain?action=edit&redlink=1", "stats": "6", "type": "Hero", "id": "TNL076", "desc": "Solemn Caine, Pilgrim of Pain\n This zealot has mounted a one-man inquisition into the darkest depths of Arcadia's dungeons. A grim slayer of the godless, he holds particular disdain for Belladonna and her vampire kin."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Cleric", "min": "2", "img_url": "", "treasure": "Cleric", "link": "/wiki/Danae_the_Slayer?action=edit&redlink=1", "stats": "6", "type": "Hero", "id": "TNL075", "desc": "Danae the Slayer\n A woman of few words, Danae is relentlessly focused on her mission: to eliminate every undead abomination in Arcadia. As long as she keeps the faith, no zombie is safe."}
{"amnt": "2", "subtitle": "-", "name": "Lightning Bolt!", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/6/69/Lightning_Bolt.PNG/revision/latest/scale-to-width-down/220?cb=20150506195921", "treasure": "-", "link": "/wiki/Lightning_Bolt!", "stats": "Adventure", "type": "Spell", "id": "TNL061", "desc": "Deal 3 damage to one Hero in your dungeon. AND If you discard another Spell card, deal 3 damage to each Hero at the entrance to your dungeon."}
{"amnt": "1", "subtitle": "-", "name": "Meddling Kids!", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/f/fd/Meddling_Kids%21.jpg/revision/latest/scale-to-width-down/220?cb=20160505214059", "treasure": "-", "link": "/wiki/Meddling_Kids!", "stats": "Build & Adventure", "type": "Spell", "id": "TNL062", "desc": "Choose a Room. Until the end of turn, it has no ability text. OR Choose a player. If three or more Heroes entered that player's dungeon this turn, that player cannot win this turn."}
{"amnt": "1", "subtitle": "Ordinary Hero", "name": "Cleric", "min": "2", "img_url": "", "treasure": "Cleric", "link": "/wiki/Elfstar?action=edit&redlink=1", "stats": "4", "type": "Hero", "id": "TNL073", "desc": "Elfstar\n Once an acolyte limited to simple orisons, Elfstar is now a true priestess who has mastered the mind bondage spell. She's accepted that nothing is more important than her spiritual growth."}
{"amnt": "2", "subtitle": "-", "name": "It's On!", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/f/fa/Its_on.PNG/revision/latest/scale-to-width-down/220?cb=20150506195349", "treasure": "-", "link": "/wiki/It%27s_On!", "stats": "Adventure", "type": "Spell", "id": "TNL059", "desc": "Kill one Hero in your dungeon who has 3 or less Health. OR If you have 3 wounds or more, kill one Hero in your dungeon."}
{"amnt": "2", "subtitle": "-", "name": "Fairy Fountain", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/c/ce/Fairy_fountain.jpg/revision/latest/scale-to-width-down/300?cb=20150415163627", "treasure": "-", "link": "/wiki/Fairy_Fountain", "stats": "Build", "type": "Spell", "id": "TNL058", "desc": "Choose a Room. Until end of turn, it does zero damage and each Hero entering it gains +1."}
{"amnt": "2", "subtitle": "-", "name": "Another Castle", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/d/d2/Another_Castle.PNG/revision/latest/scale-to-width-down/220?cb=20150506194031", "treasure": "-", "link": "/wiki/Another_Castle", "stats": "Adventure", "type": "Spell", "id": "TNL057", "desc": "Choose a Hero in your dungeon. Send that Hero to the entrance of an opponent's dungeon."}
{"amnt": "2", "subtitle": "-", "name": "Secret Stash", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Secret_Stash?action=edit&redlink=1", "stats": "Build", "type": "Spell", "id": "TNL067", "desc": "Choose a Room in your dungeon. Until end of turn, give it one extra Cleric, Fighter, Mage or Thief."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Save Point", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/8/8f/Save_point.PNG/revision/latest/scale-to-width-down/220?cb=20150506200635", "treasure": "Cleric + Mage", "link": "/wiki/Save_Point", "stats": "0", "type": "Room", "id": "TNL055", "desc": "You may destroy this Room to retrieve one Spell card from the discard pile that you played this turn."}
{"amnt": "1", "subtitle": "-", "name": "All Your Base", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/d/d8/All_Your_Base.jpg/revision/latest/scale-to-width-down/300?cb=20150427234611", "treasure": "-", "link": "/wiki/All_Your_Base", "stats": "Build", "type": "Spell", "id": "TNL056", "desc": "View an opponent's hand. You may take one Room card from that opponent."}
{"amnt": "2", "subtitle": "-", "name": "Pause", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Pause?action=edit&redlink=1", "stats": "Adventure", "type": "Spell", "id": "TNL065", "desc": "If there is a Hero in your dungeon, return it to the entrance and restore it to full Health. No Heroes may enter your dungeon until next turn."}
{"amnt": "2", "subtitle": "-", "name": "Party Up", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Party_Up?action=edit&redlink=1", "stats": "Adventure", "type": "Spell", "id": "TNL064", "desc": "Choose a dungeon. Until the end of turn, each Hero entering that dungeon gains +1"}
{"amnt": "2", "subtitle": "Monster Room", "name": "Werewolf Den", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/4/45/Werewolf_Den_1.PNG/revision/latest/scale-to-width-down/220?cb=20150506212145", "treasure": "Cleric + Fighter", "link": "/wiki/Werewolf_Den", "stats": "1", "type": "Room", "id": "TNL053", "desc": "Once per turn, you may discard a card from your hand to give one Hero +1 until end of turn."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Genie Lounge", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/9/9e/Genie_Lounge.PNG/revision/latest/scale-to-width-down/220?cb=20150506211749", "treasure": "Mage + Thief", "link": "/wiki/Genie_Lounge", "stats": "1", "type": "Room", "id": "TNL052", "desc": "When you build this Room, if you have no Spell cards in your hand, draw a Spell card."}
{"amnt": "1", "subtitle": "-", "name": "Oh, Yeah!", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Oh,_Yeah!?action=edit&redlink=1", "stats": "Build & Adventure", "type": "Spell", "id": "TNL063", "desc": "Swap the placement of two Rooms in your dungeon. OR If two or more of your Rooms have been destroyed this turn, choose and destroy one Room in any dungeon."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Bom-Boy Factory", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/7/7f/Bom-boy_factory.jpg/revision/latest/scale-to-width-down/300?cb=20140829153347", "treasure": "Fighter + Thief", "link": "/wiki/Bom-Boy_Factory", "stats": "3", "type": "Room", "id": "TNL050", "desc": "When a Hero dies in this Room or survives this Room, destroy this Room."}
{"amnt": "3", "subtitle": "Advanced Monster Room", "name": "Hatchling's Hoard", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/8/8f/Hatchling.PNG/revision/latest/scale-to-width-down/220?cb=20150506193843", "treasure": "Universal", "link": "/wiki/Hatchling%27s_Hoard", "stats": "2", "type": "Room", "id": "TNL051", "desc": "(You may build this over a room with Cleric, Fighter, Mage, or Thief treasure.)"}
{"amnt": "1", "subtitle": "Advanced Trap Room", "name": "The Smashinator", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/1/10/The_Smashinator.PNG/revision/latest/scale-to-width-down/220?cb=20150506205524", "treasure": "Thief", "link": "/wiki/The_Smashinator", "stats": "3", "type": "Room", "id": "TNL048", "desc": "Once per turn, you may destroy every other visible Room in your dungeon to give this Room +6 until end of turn."}
{"amnt": "2", "subtitle": "Advanced Trap Room", "name": "Blockpile Puzzle", "min": "-", "img_url": "", "treasure": "Thief", "link": "/wiki/Blockpile_Puzzle", "stats": "5", "type": "Room", "id": "TNL047", "desc": "At the end of each turn, destroy one Room in your dungeon."}
{"amnt": "2", "subtitle": "-", "name": "Hiring Spree", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Hiring_Spree?action=edit&redlink=1", "stats": "Build", "type": "Spell", "id": "TNL060", "desc": "Draw three Room cards, then give another player one of your Room cards."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Decapitator", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/8/8a/Decapitator.PNG/revision/latest/scale-to-width-down/220?cb=20150506204903", "treasure": "Thief", "link": "/wiki/Decapitator", "stats": "2", "type": "Room", "id": "TNL045", "desc": "During the Build phase, you may destroy this Room to choose one Room in any dungeon and remove its treasure value until end of turn."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Collapsing Bridge", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/c/c0/Collapsing.PNG/revision/latest/scale-to-width-down/220?cb=20150506033412", "treasure": "Thief", "link": "/wiki/Collapsing_Bridge", "stats": "1", "type": "Room", "id": "TNL043", "desc": "If a Hero survives this Room, until the end of turn this Room deals +3\n\nRevised: \nOnce per turn, if a Hero survives this Room, until end of turn this Room deals +3."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Wreck Room", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/f/f4/Wreck_room.jpg/revision/latest/scale-to-width-down/400?cb=20150415170212", "treasure": "Thief*2", "link": "/wiki/Wreck_Room", "stats": "1", "type": "Room", "id": "TNL041", "desc": "Once per turn, you may destroy another Room in your dungeon to draw a Room card."}
{"amnt": "1", "subtitle": "Trap Room", "name": "Bullet Builder", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/0/0d/Bullet_Builder.PNG/revision/latest/scale-to-width-down/220?cb=20150506215109", "treasure": "Thief*2", "link": "/wiki/Bullet_Builder", "stats": "1", "type": "Room", "id": "TNL040", "desc": "Once per turn, you may discard a Trap Room to give one Monster Room -1 until end of turn."}
{"amnt": "2", "subtitle": "Advanced Trap Room", "name": "Hall of Mirrors", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/7/7e/Hall_of_Mirrors.PNG/revision/latest/scale-to-width-down/220?cb=20150506210837", "treasure": "Mage", "link": "/wiki/Hall_of_Mirrors", "stats": "2", "type": "Room", "id": "TNL037", "desc": "Once per turn when an opponent plays a Spell card, draw a Spell card."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Sorcerobe School", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/a/a4/Sorcerobe_school.jpg/revision/latest/scale-to-width-down/300?cb=20150415164614", "treasure": "Mage", "link": "/wiki/Sorcerobe_School", "stats": "1", "type": "Room", "id": "TNL036", "desc": "When you build or uncover this Room, draw a Spell card."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Cursed Tomb", "min": "-", "img_url": "", "treasure": "Cleric + Thief", "link": "/wiki/Cursed_Tomb?action=edit&redlink=1", "stats": "1", "type": "Room", "id": "TNL054", "desc": "If an effect from another card causes this Room to be destroyed, each opponent must discard two Room cards."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Frostbat Cave", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/c/c9/Frostbat.PNG/revision/latest/scale-to-width-down/220?cb=20150506032706", "treasure": "Mage", "link": "/wiki/Frostbat_Cave", "stats": "2", "type": "Room", "id": "TNL033", "desc": "You may destroy this Room to deactivate one Room in any dungeon."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Observatory", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/5/57/Observatory.PNG/revision/latest/scale-to-width-down/220?cb=20150506214807", "treasure": "Mage", "link": "/wiki/Observatory", "stats": "2", "type": "Room", "id": "TNL035", "desc": "Once per turn, you may discard a Spell card to draw a Spell card."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Warp Tube", "min": "-", "img_url": "", "treasure": "Fighter + Mage", "link": "/wiki/Warp_Tube?action=edit&redlink=1", "stats": "1", "type": "Room", "id": "TNL049", "desc": "You may destroy this Room to send a Hero in this Room back to the first Room of your dungeon."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Lost Library", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/4/47/Lost_Library.PNG/revision/latest/scale-to-width-down/220?cb=20150506210419", "treasure": "Mage*2", "link": "/wiki/Lost_Library", "stats": "1", "type": "Room", "id": "TNL032", "desc": "You may destroy this Room to draw two Spell cards, then discard a Spell card."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Spiked Pit", "min": "-", "img_url": "", "treasure": "Thief", "link": "/wiki/Spiked_Pit?action=edit&redlink=1", "stats": "1", "type": "Room", "id": "TNL044", "desc": "When you build or uncover this Room, give this Room +3 until end of turn."}
{"amnt": "1", "subtitle": "Advanced Monster Room", "name": "Brainsucker Queen", "min": "-", "img_url": "", "treasure": "Mage", "link": "/wiki/Brainsucker_Queen?action=edit&redlink=1", "stats": "3", "type": "Room", "id": "TNL039", "desc": "Once per turn, if a Hero dies in this Room, draw two Spell cards, then discard a Spell card."}
{"amnt": "1", "subtitle": "Advanced Monster Room", "name": "Megaworm Burrow", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/9/92/Megaworm.PNG/revision/latest/scale-to-width-down/220?cb=20150506204345", "treasure": "Fighter", "link": "/wiki/Megaworm_Burrow", "stats": "4", "type": "Room", "id": "TNL029", "desc": "When you build this Room, choose and destroy one Advanced Room in any dungeon."}
{"amnt": "2", "subtitle": "Trap Room", "name": "Deadly Treadmill", "min": "-", "img_url": "", "treasure": "Thief", "link": "/wiki/Deadly_Treadmill?action=edit&redlink=1", "stats": "2", "type": "Room", "id": "TNL042", "desc": "Once per turn, you may discard a Room card to draw a Room card."}
{"amnt": "2", "subtitle": "Advanced Monster Room", "name": "Goblin Mess Hall", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/0/03/Goblin_Mess_Hall-0.jpg/revision/latest/scale-to-width-down/412?cb=20150324153913", "treasure": "Fighter", "link": "/wiki/Goblin_Mess_Hall", "stats": "3", "type": "Room", "id": "TNL028", "desc": "Give ever other Monster Room in your dungeon +1"}
{"amnt": "1", "subtitle": "Advanced Monster Room", "name": "Elemental Generator", "min": "-", "img_url": "", "treasure": "Mage", "link": "/wiki/Elemental_Generator?action=edit&redlink=1", "stats": "3", "type": "Room", "id": "TNL038", "desc": "This Room has +X, where X equals the number of Spell cards in your hand."}
{"amnt": "1", "subtitle": "Advanced Monster Room", "name": "The Arena", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/8/8c/The_arena.jpg/revision/latest/scale-to-width-down/300?cb=20150417060650", "treasure": "Fighter", "link": "/wiki/The_Arena", "stats": "2", "type": "Room", "id": "TNL030", "desc": "Once per turn, you may reveal a Monster Room from your hand to give this Room +X, where X is that Room's power."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Fangroot Garden", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/c/cd/Fangroot_garden.jpg/revision/latest/scale-to-width-down/300?cb=20150415164044", "treasure": "Fighter", "link": "/wiki/Fangroot_Garden", "stats": "2", "type": "Room", "id": "TNL026", "desc": "Once per turn, if a Hero dies in this Room, you may immediately build another Room in your dunegon."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Shrooman Cave", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/a/a7/Shrooman.PNG/revision/latest/scale-to-width-down/220?cb=20150506034225", "treasure": "Fighter", "link": "/wiki/Shrooman_Cave", "stats": "1", "type": "Room", "id": "TNL027", "desc": "When you build or uncover this Room, give another Monster Room +3 until end of turn."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Barbarian Hall", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/1/12/Barbarian_Hall.PNG/revision/latest/scale-to-width-down/220?cb=20150506203713", "treasure": "Fighter", "link": "/wiki/Barbarian_Hall", "stats": "3", "type": "Room", "id": "TNL024", "desc": "When you build this Room, choose and discard one Spell card (if you have any Spell cards in your hand)."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Goblin Nursery", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/2/22/Goblin_nursery.jpg/revision/latest/scale-to-width-down/300?cb=20150327002042", "treasure": "Fighter*2", "link": "/wiki/Goblin_Nursery", "stats": "1", "type": "Room", "id": "TNL023", "desc": "If the Room to the left of this is a Monster Room, give that Room +2"}
{"amnt": "1", "subtitle": "Trap Room", "name": "Dark Portal", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/4/40/Dark_Portal.PNG/revision/latest/scale-to-width-down/220?cb=20150506214133", "treasure": "Cleric*2", "link": "/wiki/Dark_Portal", "stats": "1", "type": "Room", "id": "TNL013", "desc": "Once per turn, you may discard a Spell card to choose one Room card from the discard pile and put it into your hand."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Spellslime Pit", "min": "-", "img_url": "", "treasure": "Mage", "link": "/wiki/Spellslime_Pit?action=edit&redlink=1", "stats": "2", "type": "Room", "id": "TNL034", "desc": "Whenever you play a Spell, this Room gains +1 until end of turn."}
{"amnt": "2", "subtitle": "Advanced Trap Room", "name": "Dragon Graveyard", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/f/fd/Dragon_Graveyard.PNG/revision/latest/scale-to-width-down/220?cb=20150506211322", "treasure": "Cleric", "link": "/wiki/Dragon_Graveyard", "stats": "4", "type": "Room", "id": "TNL020", "desc": "Once per turn, if you take a card from the discard pile, draw a Room card."}
{"amnt": "1", "subtitle": "Monster Room", "name": "Rust Monster Pen", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/d/d1/Rust_monster_pen.jpg/revision/latest/scale-to-width-down/300?cb=20150415162922", "treasure": "Fighter*2", "link": "/wiki/Rust_Monster_Pen", "stats": "1", "type": "Room", "id": "TNL022", "desc": "Once per turn, you may discard a Monster Room to give one Trap Room -1 until end of turn."}
{"amnt": "1", "subtitle": "Charrer of Souls", "name": "Eclipse", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/c/c9/Eclipse.jpg/revision/latest/scale-to-width-down/300?cb=20151117224436", "treasure": "Theif", "link": "/wiki/Eclipse", "stats": "525", "type": "Boss", "id": "TNL012", "desc": "Level Up:\n For the rest of the game, when you destroy a Room in your dungeon, the uncovered Room gains +3 until end of turn."}
{"amnt": "1", "subtitle": "Trap Room", "name": "Antimagic Zone", "min": "-", "img_url": "", "treasure": "Mage*2", "link": "/wiki/Antimagic_Zone?action=edit&redlink=1", "stats": "1", "type": "Room", "id": "TNL031", "desc": "You may discard this from your hand to cancel an opponent's Spell. (The Spell is not cast. Place it in the discard pile.)"}
{"amnt": "1", "subtitle": "One-Winged Demon", "name": "Angstigoth", "min": "-", "img_url": "https://vignette.wikia.nocookie.net/bossmonster/images/b/bf/Angstigoth.jpg/revision/latest/scale-to-width-down/300?cb=20150415163206", "treasure": "Thief", "link": "/wiki/Angstigoth", "stats": "475", "type": "Boss", "id": "TNL011", "desc": "Level Up:\n For the rest of the game, once per turn when you kill a Hero, draw a Room card."}
{"amnt": "2", "subtitle": "Monster Room", "name": "Spawn Point", "min": "-", "img_url": "", "treasure": "Fighter", "link": "/wiki/Spawn_Point?action=edit&redlink=1", "stats": "2", "type": "Room", "id": "TNL025", "desc": "Once per turn, if a Hero dies in this Room, draw two Room cards."}
{"amnt": "1", "subtitle": "Advanced Monster Room", "name": "Wraith's Throne", "min": "-", "img_url": "", "treasure": "Cleric", "link": "/wiki/Wraith%27s_Throne?action=edit&redlink=1", "stats": "3", "type": "Room", "id": "TNL021", "desc": "Once per turn, if a Hero dies in this Room, each opponent must discard a Spell card."}
