{"amnt": "1", "subtitle": "Thief Item", "name": "Golden Coin", "min": "-", "img_url": "", "treasure": "Thief", "link": "/wiki/Golden_Coin?action=edit&redlink=1", "stats": "-", "type": "Item", "id": "HSP004", "desc": "Power-Up:| Each time this Hero enters a Room with more than one treasure icon, give this Hero +2|Reward:| Choose any Room in your dungeon. Until end of turn, it gains Cleric, Fighter, Mage, or Thief treasure."}
{"amnt": "1", "subtitle": "Universal Item", "name": "Loyal Steed", "min": "-", "img_url": "", "treasure": "Universal", "link": "/wiki/Loyal_Steed?action=edit&redlink=1", "stats": "-", "type": "Item", "id": "HSP005", "desc": "Power-Up:| This Hero skips the first Room it would enter.|Reward:| Choose a Hero in town. Attach this Item to it and move it to any dungeon entrance."}
{"amnt": "1", "subtitle": "-", "name": "Get Over Here!", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Get_Over_Here!?action=edit&redlink=1", "stats": "Adventure", "type": "Spell", "id": "HSP007", "desc": "Choose a Hero in your dungeon. It skips the next Room it would enter. Deal 3 damage to that Hero. OR Choose an Epic Hero at the entrance to your dungeon. It skips the first four Rooms of your dungeon. Deal 10 damage to that Hero."}
{"amnt": "1", "subtitle": "Mage Item", "name": "Mana Potion", "min": "-", "img_url": "", "treasure": "Mage", "link": "/wiki/Mana_Potion?action=edit&redlink=1", "stats": "-", "type": "Item", "id": "HSP003", "desc": "Power-Up:| When this Item is attached, every player must draw and reveal a Spell card, then must discard that Spell at end of turn if it has not been played.|Reward:| Draw and reveal a Spell card. At end of turn, if you have not played that Spell, discard it."}
{"amnt": "1", "subtitle": "Fighter Item", "name": "Power Armor", "min": "-", "img_url": "", "treasure": "Fighter", "link": "/wiki/Power_Armor?action=edit&redlink=1", "stats": "-", "type": "Item", "id": "HSP002", "desc": "Power-Up:| Once per turn, one player may discard a Room card to give this Hero +3 until end of turn.|Reward:| Choose a Hero in any dungeon. You may discard a Room card to give that Hero +3 until end of turn."}
{"amnt": "1", "subtitle": "-", "name": "Inconceivable!", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Inconceivable!?action=edit&redlink=1", "stats": "Adventure", "type": "Spell", "id": "HSP008", "desc": "If you gained 2 wounds this turn, draw two Spell cards. OR If you gained 3 wounds or more this turn, draw three Spell cards."}
{"amnt": "1", "subtitle": "Cleric Item", "name": "Phoenix Feather", "min": "-", "img_url": "", "treasure": "Cleric", "link": "/wiki/Phoenix_Feather?action=edit&redlink=1", "stats": "-", "type": "Item", "id": "HSP001", "desc": "Power-Up:| When this Hero enters your dungeon, choose a face-down Hero in your scorekeeping area and return it to town.|Reward:| Choose a face-down Hero in an opponent's scorekeeping area and return it to town."}
{"amnt": "1", "subtitle": "-", "name": "Polymorph!", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Polymorph!?action=edit&redlink=1", "stats": "Adventure", "type": "Spell", "id": "HSP010", "desc": "Choose one Hero at the entrance to your dungeon. You may swap it with any Hero in town. OR If you have two other Spell cards in hand, you may swap it with a Hero at the entrance to any dungeon."}
{"amnt": "1", "subtitle": "-", "name": "Final Form!", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Final_Form!?action=edit&redlink=1", "stats": "Adventure", "type": "Spell", "id": "HSP006", "desc": "Give the last Room of your dungeon +2 until end of turn. OR If any opponent has 8 souls or more, give the last Room of your dungeon +4 until end of turn."}
{"amnt": "1", "subtitle": "-", "name": "Item Get!", "min": "-", "img_url": "", "treasure": "-", "link": "/wiki/Item_Get!?action=edit&redlink=1", "stats": "Build & Adventure", "type": "Spell", "id": "HSP009", "desc": "Reveal the top card of the Item deck. You may attach it to any Hero. OR If you have no face-up Items inyour scorekeeping area, you may instead place that Item face-up in your scorekeeping area."}
